#!/bin/bash

uid="$(id -u)"
gid="$(id -g)"
dir="$(pwd)"

set -e

mkdir --parents ~/.conan/data
touch ~/.conan/.conan.db
touch ~/.conan/registry.txt

set -x
docker run -it --rm \
    --net=host \
    -w "${dir}" \
    -e uid="${uid}" \
    -e gid="${gid}" \
    -v "$HOME/.ssh/id_rsa:/home/captain/.ssh/id_rsa" \
    -v "$HOME/.ssh/known_hosts:/home/captain/.ssh/known_hosts" \
    -v "${dir}:${dir}" \
    -v "$HOME/.conan/data:/home/captain/.conan/data" \
    -v "$HOME/.conan/registry.txt:/home/captain/.conan/registry.txt" \
    -v "$HOME/.conan/.conan.db:/home/captain/.conan/.conan.db" \
    wsbu/toolchain-linaro "$@"

